# 模型设置
model_name_or_path: /scratch/nishang/models/Qwen3-14B-Base-add-pad-tok
finetuning_type: full
stage: pt

# FSDP配置
fsdp: "full_shard auto_wrap"
fsdp_config:
  fsdp_transformer_layer_cls_to_wrap: "Qwen3DecoderLayer"  # Qwen模型的层名称
  fsdp_backward_prefetch: "backward_pre"
  fsdp_forward_prefetch: true
  fsdp_use_orig_params: true
  fsdp_cpu_ram_efficient_loading: true
  fsdp_auto_wrap_policy: "TRANSFORMER_BASED_WRAP"
  fsdp_sharding_strategy: 1  # FULL_SHARD
  fsdp_state_dict_type: "SHARDED_STATE_DICT"
  fsdp_activation_checkpointing: true  # 启用激活检查点以节省内存

# 数据设置
dataset: identity
tokenized_path: /scratch/nishang/mid-train-data/merged_dataset_v1_less_32k
template: qwen3-pt
cutoff_len: 32768
max_samples: null
overwrite_cache: false
preprocessing_num_workers: 8


do_train: true
flash_attn: "fa2"
# 训练参数
per_device_train_batch_size: 1  # FSDP可以使用更大的batch size
gradient_accumulation_steps: 16
learning_rate: 1.0e-5
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.01

# 优化器和精度
optim: adamw_torch
fp16: false
bf16: true  # FSDP推荐使用bf16

# 梯度和内存管理
max_grad_norm: 1.0
dataloader_pin_memory: false
dataloader_num_workers: 8

# 保存策略
output_dir: /scratch/nishang/mid-train-ckpt/qwen-14b-base-mid-train-v1-32k-pad-tok
save_strategy: steps
save_steps: 50
save_total_limit: 3

report_to: wandb
run_name: qwen-14b-base-mid-train-v1-32k-pad-tok
logging_steps: 1
